export const API_KEYS = {
  GOOGLE: process.env.REACT_APP_GOOGLE_API_KEY,
  GOOGLE_SEARCH_ENGINE_ID: process.env.REACT_APP_GOOGLE_SEARCH_ENGINE_ID,
  OPENAI: process.env.REACT_APP_OPENAI_API_KEY,
  ELEVENLABS: process.env.REACT_APP_ELEVENLABS_API_KEY
}; 